### ISSUE TITLE
Decoder don't support new timestamp + metadata log record format

### ISSUE THREAD

**Issue by edsiper** [fluent/fluent-bit-go#66]
In Fluent Bit we introduced a new format for log records:

```
[[timestamp, {METADATA}], {EVENT}]
```

Fluent Bit code base has been updated to work with the old format and the new one. But the golang decoder is not updated and needs to be fixed.

**Comment by cosmo0920** [comment]
I tested this for in_dummy and gstdout that is built by this Golang interface.
But, it works.
Is there a fluent-bit configuration any containing for this issue? Or, minimal reproducible steps?

**Comment by edsiper** [comment]
How do you extract metadata by using the golang output decoder?

**Comment by cosmo0920** [comment]
Ah, sorry for confusing. I misunderstood for this issue and I wrote down a patch for handling this issue.

**Comment by randomizedcoder** [comment]
Tried to add a little more to the tests, but it fails.
https://github.com/fluent/fluent-bit-go/pull/69

**Comment by rasturic** [comment]
I'm looking forward to the fix as our company depends on https://github.com/logzio/fluent-bit-logzio-output which uses this.

**Comment by randomizedcoder** [comment]
I realized today that Fluentbit can send an array messages, rather than single message at a time.  This is probably good for performance (batching), but there are no tests with this type.  I only noticed because I increased the message rate of my test.

I just added a few more test data files here
https://github.com/randomizedcoder/fluent-bit-go/tree/tweaks/output/testdata

Decoding the msgpack to yaml, you can see the data1 file turns into data1.yaml.  The second record starts here, for example
https://github.com/randomizedcoder/fluent-bit-go/blob/tweaks/output/testdata/data1.yaml#L527
